makelaarsland:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: analytics-engineers
      dataset: makelaarsland
      threads: 3
      timeout_seconds: 300
      location: EU
      priority: interactive
