version: 2
models:
  - name: base_makelaarsland
    description: ""
    columns:
      - name: url
        description: ""

      - name: city
        description: ""

      - name: date
        description: ""

      - name: roof
        description: ""

      - name: floor
        description: ""

      - name: price
        description: ""

      - name: brands
        description: ""

      - name: garden
        description: ""

      - name: plaats
        description: ""

      - name: status
        description: ""

      - name: volume
        description: ""

      - name: heating
        description: ""

      - name: parking
        description: ""

      - name: storage
        description: ""

      - name: zijtuin
        description: ""

      - name: capacity
        description: ""

      - name: date_tmp
        description: ""

      - name: delivery
        description: ""

      - name: location
        description: ""

      - name: voortuin
        description: ""

      - name: amenities
        description: ""

      - name: back_yard
        description: ""

      - name: isolation
        description: ""

      - name: plot_area
        description: ""

      - name: build_year
        description: ""

      - name: house_type
        description: ""

      - name: streetname
        description: ""

      - name: warm_water
        description: ""

      - name: garage_type
        description: ""

      - name: postal_code
        description: ""

      - name: sun_terrace
        description: ""

      - name: build_period
        description: ""

      - name: energy_class
        description: ""

      - name: heating_type
        description: ""

      - name: outside_size
        description: ""

      - name: patio_atrium
        description: ""

      - name: rooms_amount
        description: ""

      - name: floors_amount
        description: ""

      - name: kvk_insurance
        description: ""

      - name: bijzonderheden
        description: ""

      - name: appartment_type
        description: ""

      - name: balcony_terrace
        description: ""

      - name: garden_location
        description: ""

      - name: kvk_repair_plan
        description: ""

      - name: bathrooms_amount
        description: ""

      - name: external_storage
        description: ""

      - name: kvk_registration
        description: ""

      - name: construction_type
        description: ""

      - name: kvk_reserve_funds
        description: ""

      - name: other_inhoouse_spaces
        description: ""

      - name: kvk_monthly_payment
        description: ""

      - name: kvk_yearly_meeting
        description: ""

      - name: bathroom_amenities
        description: ""

      - name: living_size
        description: ""

      - name: id
        description: ""
