version: 2
models:
  - name: base_makelaarsland
    description: ""
    columns:
      - name: url
        description: ""

      - name: city
        description: ""

      - name: date
        description: ""

      - name: roof
        description: ""

      - name: floor
        description: ""

      - name: price
        description: ""

      - name: status
        description: ""

      - name: volume
        description: ""

      - name: heating
        description: ""

      - name: parking
        description: ""

      - name: delivery
        description: ""

      - name: location
        description: ""

      - name: amenities
        description: ""

      - name: isolation
        description: ""

      - name: build_year
        description: ""

      - name: streetname
        description: ""

      - name: warm_water
        description: ""

      - name: living_size
        description: ""

      - name: postal_code
        description: ""

      - name: heating_type
        description: ""

      - name: outside_size
        description: ""

      - name: rooms_amount
        description: ""

      - name: floors_amount
        description: ""

      - name: kvk_insurance
        description: ""

      - name: appartment_type
        description: ""

      - name: balcony_terrace
        description: ""

      - name: kvk_repair_plan
        description: ""

      - name: bathrooms_amount
        description: ""

      - name: external_storage
        description: ""

      - name: kvk_registration
        description: ""

      - name: construction_type
        description: ""

      - name: kvk_reserve_funds
        description: ""

      - name: bathroom_amenities
        description: ""

      - name: kvk_yearly_meeting
        description: ""

      - name: _ab_source_file_url
        description: ""

      - name: kvk_monthly_payment
        description: ""

