

with source as (
    select * from {{ source('bigquery', 'makelaarsland_raw') }}
)

select 
    json_extract_scalar(_airbyte_data, "$['url']") as url,
    json_extract_scalar(_airbyte_data, "$['city']") as city,
    json_extract_scalar(_airbyte_data, "$['date']") as date,
    json_extract_scalar(_airbyte_data, "$['roof']") as roof,
    json_extract_scalar(_airbyte_data, "$['floor']") as floor,
    json_extract_scalar(_airbyte_data, "$['price']") as price,
    json_extract_scalar(_airbyte_data, "$['brands']") as brands,
    json_extract_scalar(_airbyte_data, "$['garden']") as garden,
    json_extract_scalar(_airbyte_data, "$['plaats']") as plaats,
    json_extract_scalar(_airbyte_data, "$['status']") as status,
    json_extract_scalar(_airbyte_data, "$['volume']") as volume,
    json_extract_scalar(_airbyte_data, "$['heating']") as heating,
    json_extract_scalar(_airbyte_data, "$['parking']") as parking,
    json_extract_scalar(_airbyte_data, "$['storage']") as storage,
    json_extract_scalar(_airbyte_data, "$['zijtuin']") as zijtuin,
    json_extract_scalar(_airbyte_data, "$['capacity']") as capacity,
    json_extract_scalar(_airbyte_data, "$['date_tmp']") as date_tmp,
    json_extract_scalar(_airbyte_data, "$['delivery']") as delivery,
    json_extract_scalar(_airbyte_data, "$['location']") as location,
    json_extract_scalar(_airbyte_data, "$['voortuin']") as voortuin,
    json_extract_scalar(_airbyte_data, "$['amenities']") as amenities,
    json_extract_scalar(_airbyte_data, "$['back_yard']") as back_yard,
    json_extract_scalar(_airbyte_data, "$['isolation']") as isolation,
    json_extract_scalar(_airbyte_data, "$['plot_area']") as plot_area,
    json_extract_scalar(_airbyte_data, "$['build_year']") as build_year,
    json_extract_scalar(_airbyte_data, "$['house_type']") as house_type,
    json_extract_scalar(_airbyte_data, "$['streetname']") as streetname,
    json_extract_scalar(_airbyte_data, "$['warm_water']") as warm_water,
    json_extract_scalar(_airbyte_data, "$['garage_type']") as garage_type,
    json_extract_scalar(_airbyte_data, "$['postal_code']") as postal_code,
    json_extract_scalar(_airbyte_data, "$['sun_terrace']") as sun_terrace,
    json_extract_scalar(_airbyte_data, "$['build_period']") as build_period,
    json_extract_scalar(_airbyte_data, "$['energy_class']") as energy_class,
    json_extract_scalar(_airbyte_data, "$['heating_type']") as heating_type,
    json_extract_scalar(_airbyte_data, "$['outside_size']") as outside_size,
    json_extract_scalar(_airbyte_data, "$['patio_atrium']") as patio_atrium,
    json_extract_scalar(_airbyte_data, "$['rooms_amount']") as rooms_amount,
    json_extract_scalar(_airbyte_data, "$['floors_amount']") as floors_amount,
    json_extract_scalar(_airbyte_data, "$['kvk_insurance']") as kvk_insurance,
    json_extract_scalar(_airbyte_data, "$['bijzonderheden']") as bijzonderheden,
    json_extract_scalar(_airbyte_data, "$['appartment_type']") as appartment_type,
    json_extract_scalar(_airbyte_data, "$['balcony_terrace']") as balcony_terrace,
    json_extract_scalar(_airbyte_data, "$['garden_location']") as garden_location,
    json_extract_scalar(_airbyte_data, "$['kvk_repair_plan']") as kvk_repair_plan,
    json_extract_scalar(_airbyte_data, "$['bathrooms_amount']") as bathrooms_amount,
    json_extract_scalar(_airbyte_data, "$['external_storage']") as external_storage,
    json_extract_scalar(_airbyte_data, "$['kvk_registration']") as kvk_registration,
    json_extract_scalar(_airbyte_data, "$['construction_type']") as construction_type,
    json_extract_scalar(_airbyte_data, "$['kvk_reserve_funds']") as kvk_reserve_funds,
    json_extract_scalar(_airbyte_data, "$['_ab_source_file_url']") as _ab_source_file_url,
    json_extract_scalar(_airbyte_data, "$['other_inhoouse_spaces']") as other_inhoouse_spaces,
    json_extract_scalar(json_extract(_airbyte_data,"$['_ab_additional_properties']"), "$['kvk_monthly_payment']") as kvk_monthly_payment,
    json_extract_scalar(json_extract(_airbyte_data,"$['_ab_additional_properties']"), "$['kvk_yearly_meeting']") as kvk_yearly_meeting,
    json_extract_scalar(json_extract(_airbyte_data,"$['_ab_additional_properties']"), "$['bathroom_amenities']") as bathroom_amenities,
    json_extract_scalar(json_extract(_airbyte_data,"$['_ab_additional_properties']"), "$['living_size']") as living_size,
    json_extract_scalar(_airbyte_data, "$['_ab_source_file_last_modified']") as _ab_source_file_last_modified,
    _airbyte_ab_id,
    _airbyte_emitted_at,
    CURRENT_TIMESTAMP() as _airbyte_normalized_at
from source