with base as (
    select * from {{ ref('base_makelaarsland') }}
),

final as (
    select
        id,
        url,
        city,
        date,
        roof,
        floor,
        brands,
        garden,
        plaats,
        status,
        volume,
        heating,
        parking,
        storage,
        zijtuin,
        capacity,
        date_tmp,
        delivery,
        location,
        voortuin,
        amenities,
        back_yard,
        isolation,
        plot_area,
        build_year,
        house_type,
        streetname,
        warm_water,
        garage_type,
        postal_code,
        sun_terrace,
        build_period,
        energy_class,
        heating_type,
        outside_size,
        patio_atrium,
        rooms_amount,
        floors_amount,
        kvk_insurance,
        bijzonderheden,
        appartment_type,
        balcony_terrace,
        garden_location,
        kvk_repair_plan,
        bathrooms_amount,
        external_storage,
        kvk_registration,
        construction_type,
        kvk_reserve_funds,
        _ab_source_file_url,
        other_inhoouse_spaces,
        kvk_monthly_payment,
        kvk_yearly_meeting,
        bathroom_amenities,
        living_size,
        cast(REGEXP_EXTRACT(base.price, r'\d+') as int) as price
    from base
)

select * from final